export interface IntentDefinition {
  name: string;
  patterns: string[];
  parameterExtractors?: Array<{
    paramName: string;
    regex: RegExp;
  }>;
}

export const DEFAULT_INTENTS: IntentDefinition[] = [
  {
    name: 'OPEN_APPLICATION',
    patterns: [
      // English
      'open chrome',
      'launch chrome',
      'start chrome',
      'open edge',
      'launch edge',
      'start edge',
      'open microsoft edge',
      'open file explorer',
      'open explorer',
      'launch file explorer',
      'start file explorer',
      'open vs code',
      'open vscode',
      'open visual studio code',
      'launch vs code',
      'launch visual studio code',
      'start vs code',
      'open notepad',
      'launch notepad',
      'start notepad',
      'open app',
      'open application',
      'launch application',
      // Turkish
      'chrome u aç',
      'chrome aç',
      'chrome u ac',
      'chrome ac',
      'google chrome aç',
      'edge i aç',
      'edge aç',
      'edge i ac',
      'edge ac',
      'microsoft edge aç',
      'dosya gezgini ni aç',
      'dosya gezgini aç',
      'dosya gezginini aç',
      'dosya gezginini ac',
      'explorer ı aç',
      'explorer aç',
      'dosya yöneticisini aç',
      'vs code u aç',
      'visual studio code u aç',
      'vs code aç',
      'visual studio code aç',
      'code u aç',
      'vscode aç',
      'notepad i aç',
      'notepad aç',
      'not defteri ni aç',
      'not defteri aç',
      'not defterini aç',
      'uygulama aç',
      'program aç',
    ],
  },
  {
    name: 'BRING_TO_FRONT',
    patterns: [
      // English
      'bring chrome to front',
      'switch to chrome',
      'focus chrome',
      'bring edge to front',
      'switch to edge',
      'focus edge',
      'bring vs code to front',
      'switch to vs code',
      'switch to visual studio code',
      'focus vs code',
      'bring notepad to front',
      'switch to notepad',
      'focus notepad',
      'bring file explorer to front',
      'switch to file explorer',
      'bring explorer to front',
      'bring to front',
      'switch window',
      // Turkish
      'chrome u öne getir',
      'chrome a geç',
      'chrome u ön plana getir',
      'chrome öne getir',
      'edge i öne getir',
      'edge e geç',
      'edge i ön plana getir',
      'vs code u öne getir',
      'vs code a geç',
      'visual studio code u öne getir',
      'visual studio code a geç',
      'notepad i öne getir',
      'notepad e geç',
      'not defterini öne getir',
      'not defterine geç',
      'dosya gezginini öne getir',
      'dosya gezginine geç',
      'öne getir',
      'ön plana getir',
      'pencereye geç',
    ],
  },
  {
    name: 'MINIMIZE_WINDOW',
    patterns: [
      // English
      'minimize current window',
      'minimize window',
      'minimize active window',
      'minimize this window',
      'minimize',
      // Turkish
      'pencereyi küçült',
      'pencereyi simge durumuna küçült',
      'ekranı küçült',
      'pencereyi simge durumuna getir',
      'küçült',
      'şu pencereyi küçült',
      'mevcut pencereyi küçült',
    ],
  },
  {
    name: 'MAXIMIZE_WINDOW',
    patterns: [
      // English
      'maximize current window',
      'maximize window',
      'maximize active window',
      'maximize this window',
      'maximize',
      'fullscreen window',
      // Turkish
      'pencereyi büyüt',
      'pencereyi ekranı kapla',
      'ekranı büyüt',
      'tam ekran yap',
      'pencereyi tam ekran yap',
      'büyüt',
      'şu pencereyi büyüt',
      'mevcut pencereyi büyüt',
    ],
  },
  {
    name: 'CLOSE_WINDOW',
    patterns: [
      // English
      'close current window',
      'close window',
      'close active window',
      'close this window',
      'close',
      // Turkish
      'pencereyi kapat',
      'şu pencereyi kapat',
      'mevcut pencereyi kapat',
      'aktif pencereyi kapat',
      'pencere kapat',
    ],
  },
  {
    name: 'MOVE_MOUSE',
    patterns: [
      // English
      'move mouse',
      'move mouse to',
      'move cursor',
      'move cursor to',
      'set cursor position',
      // Turkish
      'fareyi taşı',
      'fareyi hareket ettir',
      'imleci taşı',
      'fareyi konumuna taşı',
      'fareyi konumlandır',
    ],
  },
  {
    name: 'MOUSE_CLICK',
    patterns: [
      // English
      'left click',
      'click mouse',
      'click',
      'single click',
      'right click',
      'context click',
      'double click',
      'double left click',
      // Turkish
      'sol tıkla',
      'sol tık',
      'fare sol tık',
      'tıkla',
      'fare ile tıkla',
      'sağ tıkla',
      'sağ tık',
      'fare sağ tık',
      'çift tıkla',
      'çift tık',
      'fare çift tık',
    ],
  },
  {
    name: 'TYPE_TEXT',
    patterns: [
      // English
      'type',
      'type text',
      'write text',
      'type message',
      // Turkish
      'metin yaz',
      'yaz',
      'metni yaz',
      'yazı yaz',
    ],
  },
  {
    name: 'PRESS_KEY',
    patterns: [
      // English
      'press enter',
      'hit enter',
      'enter key',
      'press key enter',
      'press tab',
      'hit tab',
      'tab key',
      'press esc',
      'press escape',
      'hit escape',
      'hit esc',
      'escape key',
      'esc key',
      'press key',
      // Turkish
      'enter a bas',
      'enter tuşuna bas',
      'enter a tıkla',
      'entera bas',
      'tab a bas',
      'tab tuşuna bas',
      'taba bas',
      'esc e bas',
      'escape e bas',
      'esc tuşuna bas',
      'escape tuşuna bas',
      'esce bas',
      'tuşa bas',
    ],
  },
  {
    name: 'KEY_SHORTCUT',
    patterns: [
      // English
      'ctrl c',
      'ctrl+c',
      'control c',
      'copy',
      'copy to clipboard',
      'ctrl v',
      'ctrl+v',
      'control v',
      'paste',
      'paste from clipboard',
      'ctrl a',
      'ctrl+a',
      'control a',
      'select all',
      // Turkish
      'kopyala',
      'yapıştır',
      'yapistir',
      'hepsini seç',
      'tümünü seç',
      'tumunu sec',
    ],
  },
  {
    name: 'READ_SCREEN',
    patterns: [
      // English
      'read screen',
      'what do you see',
      'analyze this screen',
      'look at the screen',
      'read this screen',
      'what is on my screen',
      'ocr screen',
      'read text on screen',
      // Turkish
      'ekranı oku',
      'ekrani oku',
      'şu ekrana bak',
      'su ekrana bak',
      'ekrana bak',
      'bu ekranda ne var',
      'ekranda ne var',
      'bana bunu açıkla',
      'bana bunu acikla',
      'bunu açıkla',
      'ekrandaki yazıları oku',
      'ekrandaki metni oku',
    ],
  },
  {
    name: 'CAPTURE_SCREEN',
    patterns: [
      // English
      'capture',
      'capture screen',
      'take screenshot',
      'take a screenshot',
      'screenshot',
      'screen capture',
      'save screen',
      // Turkish
      'ekran görüntüsü al',
      'ekran goruntusu al',
      'ekran görüntüsü çek',
      'ekran resmi al',
      'screenshot al',
      'ss al',
      'ekranı kaydet',
    ],
  },
  {
    name: 'LIST_WINDOWS',
    patterns: [
      // English
      'list windows',
      'open windows',
      'show windows',
      'what windows are open',
      'active windows',
      'running applications',
      // Turkish
      'hangi pencereler açık',
      'hangi pencereler acik',
      'açık pencereler',
      'acik pencereler',
      'pencereleri listele',
      'açık uygulamalar',
      'hangi programlar açık',
    ],
  },
  {
    name: 'OPEN_FILE',
    patterns: [
      // English
      'open file',
      'open the file',
      // Turkish
      'dosyayı aç',
      'dosyayi ac',
      'dosya aç',
    ],
  },
  {
    name: 'HELP',
    patterns: [
      // English
      'help',
      'what can you do',
      'commands',
      'available commands',
      // Turkish
      'yardım',
      'yardim',
      'neler yapabilirsin',
      'komutlar',
    ],
  },
  {
    name: 'NAVIGATE',
    patterns: [
      // English
      'go to github',
      'go to github.com',
      'navigate to github',
      'open github',
      'open website',
      'go to url',
      'navigate to url',
      'go to youtube',
      'go to google',
      // Turkish
      'github a git',
      'github\'a git',
      'githuba git',
      'youtube a git',
      'youtube\'a git',
      'youtubeya git',
      'google a git',
      'google\'a git',
      'siteye git',
      'web sitesine git',
      'sayfaya git',
    ],
  },
  {
    name: 'OPEN_FOLDER',
    patterns: [
      // English
      'open folder',
      'open directory',
      'open path',
      // Turkish
      'klasörü aç',
      'klasorunu ac',
      'klasörü ac',
      'klasör aç',
      'dizini aç',
      'klasörünü aç',
      'klasorunu aç',
    ],
  },
  {
    name: 'NEW_TAB',
    patterns: [
      // English
      'new tab',
      'open new tab',
      'create tab',
      'add tab',
      // Turkish
      'yeni sekme aç',
      'yeni sekme',
      'sekme aç',
      'yeni sekme ac',
      'sekme ac',
    ],
  },
  {
    name: 'CLOSE_TAB',
    patterns: [
      // English
      'close tab',
      'close current tab',
      'close the tab',
      // Turkish
      'sekmeyi kapat',
      'sekme kapat',
      'bu sekmeyi kapat',
      'sekmeyi kapa',
    ],
  },
  {
    name: 'SWITCH_TAB',
    patterns: [
      // English
      'switch tab',
      'switch to tab',
      'change tab',
      'go to tab',
      // Turkish
      'sekmeye geç',
      'sekme değiştir',
      'sekmeyi değiştir',
      'sekmeye gec',
    ],
  },
  {
    name: 'RELOAD_PAGE',
    patterns: [
      // English
      'reload page',
      'refresh page',
      'reload this page',
      'reload',
      'refresh',
      // Turkish
      'bu sayfayı yenile',
      'sayfayı yenile',
      'yenile',
      'sayfayi yenile',
      'bu sayfayi yenile',
      'sayfayı tazele',
    ],
  },
  {
    name: 'BACK',
    patterns: [
      // English
      'go back',
      'back',
      'previous page',
      'return to previous page',
      // Turkish
      'önceki sayfaya dön',
      'onceki sayfaya don',
      'geri git',
      'geri dön',
      'geri don',
      'önceki sayfa',
    ],
  },
  {
    name: 'FORWARD',
    patterns: [
      // English
      'go forward',
      'forward',
      'next page',
      // Turkish
      'sonraki sayfaya git',
      'ileri git',
      'ileri dön',
      'sonraki sayfa',
    ],
  },
  {
    name: 'GET_CURRENT_URL',
    patterns: [
      // English
      'current url',
      'get url',
      'what is the url',
      'show url',
      // Turkish
      'geçerli url',
      'hangi sitedeyim',
      'hangi sayfadayım',
      'url nedir',
      'gecerli url',
    ],
  },
  {
    name: 'READ_DOM',
    patterns: [
      // English
      'read dom',
      'read web page',
      'inspect dom',
      'inspect web page',
      'read page dom',
      'get dom',
      // Turkish
      'sayfayı oku',
      'web sayfasını oku',
      'sayfa içeriğini oku',
      'dom oku',
      'domu oku',
      'sayfayi oku',
    ],
  },
  {
    name: 'GET_BUTTONS',
    patterns: [
      // English
      'how many buttons are on this page',
      'how many buttons',
      'get buttons',
      'list buttons',
      'find all buttons',
      'show buttons',
      // Turkish
      'bu sayfada kaç buton var',
      'kaç buton var',
      'sayfada kaç buton var',
      'sayfadaki butonlar',
      'butonları listele',
      'butonları göster',
      'butonları bul',
    ],
  },
  {
    name: 'GET_FORMS',
    patterns: [
      // English
      'is there a form on this page',
      'is there a form',
      'is there any form',
      'get forms',
      'list forms',
      'find forms',
      'forms on this page',
      // Turkish
      'bu sayfada form var mı',
      'sayfada form var mı',
      'form var mı',
      'formları bul',
      'formları listele',
      'formları göster',
    ],
  },
  {
    name: 'GET_INPUTS',
    patterns: [
      // English
      'get inputs',
      'list inputs',
      'find inputs',
      'show inputs',
      'input fields',
      // Turkish
      'inputları bul',
      'giriş alanlarını bul',
      'inputları listele',
      'sayfadaki inputlar',
      'giriş kutularını bul',
    ],
  },
  {
    name: 'GET_LINKS',
    patterns: [
      // English
      'get links',
      'list links',
      'find links',
      'show links',
      // Turkish
      'linkleri bul',
      'bağlantıları getir',
      'linkleri listele',
      'sayfadaki linkler',
    ],
  },
  {
    name: 'GET_VISIBLE_TEXT',
    patterns: [
      // English
      'get visible text',
      'read visible text',
      'page text',
      'get text',
      // Turkish
      'görünür metni al',
      'sayfadaki yazıları oku',
      'sayfa metnini oku',
      'görünür metin',
    ],
  },
  {
    name: 'QUERY_DOM',
    patterns: [
      // English
      'find login form',
      'find form',
      'find email input',
      'find email field',
      'find password box',
      'find password input',
      'find login button',
      'find search button',
      'find button login',
      'find textbox search',
      'find link github',
      'find input email',
      'find button',
      'find input',
      'find link',
      'find textbox',
      // Turkish
      'giriş formunu bul',
      'giris formunu bul',
      'login formunu bul',
      'email alanını bul',
      'email alanini bul',
      'e posta alanını bul',
      'şifre kutusunu bul',
      'sifre kutusunu bul',
      'parola kutusunu bul',
      'login butonunu bul',
      'giriş butonunu bul',
      'ara butonunu bul',
      'search kutusunu bul',
      'arama kutusunu bul',
      'butonu bul',
      'kutuyu bul',
    ],
  },
];
